### PR TITLE
Update BMW ConnectedDrive alert to 2021.8.8

### PR DESCRIPTION
**Pull request by rikroe**

### CODE REVIEW

**Comment by rikroe** [comment]
Is there any chance to style the table a little bit such as 
- making the table 100% width?
- add a visible grid?

**Comment by frenck** [comment]
> Is there any chance to style the table a little bit such as

No that is not possible.
However, considering 3 regions, just 3 chapters will work as well, with a list of checkboxes in each of them to indicate what works and what not.

**Comment by rikroe** [comment]
I understand about reporting the on the last version only, but I want to make clear that apparently we introduced a bug to the `china` region, so they have to keep the old version until we sorted this out.

**Review by frenck — APPROVED** [review]
Thanks, @rikroe 👍

**Pull request merged**
