### PR TITLE
Add warnig for vicare

### PR DESCRIPTION
**Pull request by balloob**

### CODE REVIEW

**Comment by h-teske** [comment]
I guess the warning can now be removed after fixing the issue...

**Comment by frenck** [comment]
The fix hasn't been released yet

**Comment by h-teske** [comment]
Is there a schedule for when the fix will be released? Can't wait to integrate it ;-)

**Comment by frenck** [comment]
If you have general questions, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Pull request merged**
