### PR TITLE
Delete ziggo_mediabox_xl.markdown

### PR DESCRIPTION
**Pull request by wrt54g**
This deprecation didn't happen. I guess this alert can be removed?

### CODE REVIEW

**Review by frenck — APPROVED** [review]
Yeah, agree, thanks  @wrt54g 👍

**Comment by wrt54g** [comment]
@frenck When will this alert be removed from the alerts site? It's still in the alerts.json file, I can't find that anywhere in this repository.

**Comment by frenck** [comment]
@wrt54g Our websites are cached, the changes will become visible over time.

**Comment by wrt54g** [comment]
> @wrt54g Our websites are cached, the changes will become visible over time.

Okay

**Pull request merged**
