### PR TITLE
Remove Tuya alert

### PR DESCRIPTION
**Pull request by frenck**
Tuya has informed us the issues are resolved, thus this alert can be removed.

closes home-assistant/core#60034

### CODE REVIEW

**Review by ludeeus — APPROVED** [review]

**Comment by vdbosch** [comment]
Frenck, not all problems are solved with Tuya. With Zigbee lamps the dimming is not working!!
On/off OK, Color temp. is working, but brightness NOT at all.

**Comment by frenck** [comment]
> Frenck, not all problems are solved with Tuya. With Zigbee lamps the dimming is not working!!
> On/off OK, Color temp. is working, but brightness NOT at all.

Right... but this was a different issue...

**Comment by vdbosch** [comment]
It was working with the new Tuya (which version I don’t remember), but OK if issue is still open than it will be probably fixed soon.

**Comment by frenck** [comment]
> It was working with the new Tuya (which version I don’t remember), but OK if issue is still open than it will be probably fixed soon.

You are responding on an alert PR which is in no way related to anything you are saying.

Please check if there is an related issue for you problem open already and track that, or, in case you weren't able to find a related issue: Create an issue report.

Thanks 👍

**Pull request merged**
